Feature/xbox teleop usb check
hello-robot/stretch_body pull request #162
Opened 2022-09-28 02:42 UTC by hello-fazil

This PR introduces a polling step to the [stretch_xbox_controller_teleop.py](https://github.com/hello-robot/stretch_body/blob/feature/xbox_teleop_usb_check/tools/bin/stretch_xbox_controller_teleop.py#L385:L414) script which waits for all the hello* USB devices to be found under `/dev` directory before initiating a Robot() class object.

2022-09-28 18:04 UTC, hello-binit requested changes

2022-09-28 18:04 UTC, hello-binit commented on tools/bin/stretch_xbox_controller_teleop.py
> +def check_usb_devices(wait_timeout=5):
Should return boolean `all_found`.

2022-09-28 18:04 UTC, hello-binit commented on tools/bin/stretch_xbox_controller_teleop.py
> +    check_usb_devices(wait_timeout=5)
If this method fails, let's emit some warning to the user. Maybe beep 3 times? @aedsinger

2022-09-29 00:32 UTC, hello-fazil commented on tools/bin/stretch_xbox_controller_teleop.py
> +def check_usb_devices(wait_timeout=5):
Done!

2022-09-29 20:58 UTC, hello-binit approved these changes
We can add a triple beep later if it seems necessary. Otherwise, I think these changes are good to merge!

2022-09-29 22:14 UTC, merged